### PR TITLE
Use native npm commands

### LINKED ISSUE #1: Checking one of my packages returns 401 error
When I try this with one of my packages, I get an error

```bash
❯ f @codedungeon/messenger

   error: unauthorized 401
```

### PR DESCRIPTION
**Pull request by FDiskas**
fixes: #1 #2 #3

### CODE REVIEW

**Comment by rousan** [comment]
Hey @FDiskas,

Thanks for your PR. But using shell command to get package data is not a stable solution as you might face problem to identify errors e.g. package not found or any internal errors, always prefer to use programmatical API instead of CLI command.
As an instance, do you prefer to use MySQL CLI command to fetch data instead of mysql programming API in your application?

**Comment by FDiskas** [comment]
reinventing the wheel

**Comment by FDiskas** [comment]
How you going to solve feature issues like: Private modules, custom registry like `bitsrc` provides.
And about MYSQL - if you need just single stuff from mysql I wil use mysql cli instead of some big and useless wrapper. It's a good example in your repo `lodash` and `babel`. Why it is used if it's not used? :)

**Comment by rousan** [comment]
Hey @FDiskas, you pointed out some unnecessary deps which needs to be removed, thanks for that.
I am not thinking about private modules, custom registry.

**Comment by FDiskas** [comment]
@rousan Should I resolve conflicts or delete this pull request?

**Comment by rousan** [comment]
Closing it.

**Pull request closed without merging**
